new exception is added.
Iotiq-Erste/commons-module pull request #31
Opened 2024-03-04 11:37 UTC by ozgur-erste

2024-03-05 05:51 UTC, inciotiq requested changes

2024-03-05 05:51 UTC, inciotiq commented on src/main/java/com/iotiq/commons/exceptions/UnprocessableEntityException.java
> +public class UnprocessableEntityException extends ApplicationException {
This exception would work better if it was in the application package. Because then we can pass the `ConstraintViolationEntry` to it.

2024-03-05 05:51 UTC, inciotiq commented on src/main/java/com/iotiq/commons/exceptions/UnprocessableEntityException.java
> +        super(HttpStatus.UNPROCESSABLE_ENTITY, "unprocessableEntity", new LinkedList<>(), new Object[]{});
Http status code `422 Unprocessable Entity` might be inappropriate here. I searched for the usual practice in case of validation errors and it seems the most common practice is to return `400 Bad Request`, `403 Forbidden` or `409 Conflict`. Can you also check what springmvc returns in case of validation errors?

https://stackoverflow.com/questions/3290182/which-status-code-should-i-use-for-failed-validations-or-invalid-duplicates

2024-03-05 05:51 UTC, inciotiq commented on src/main/java/com/iotiq/commons/config/ExceptionHandlerAdvice.java
> +    public ResponseEntity<Object> handleApplicationException(UnprocessableEntityException exception, @NonNull WebRequest request) {
```suggestion
    public ResponseEntity<Object> handleUnprocessableEntityException(UnprocessableEntityException exception, @NonNull WebRequest request) {
```

2024-03-05 05:51 UTC, inciotiq commented on src/main/java/com/iotiq/commons/config/ExceptionHandlerAdvice.java
> +    }
Can you use `Ctrl+Alt+L` before committing changes to reformat the file, please?

2024-03-05 05:53 UTC, inciotiq commented
Can you explain the contents of the merge request in the description and give it a more descriptive title please?

2024-03-05 06:59 UTC, ozgur-erste commented on src/main/java/com/iotiq/commons/exceptions/UnprocessableEntityException.java
> +public class UnprocessableEntityException extends ApplicationException {
in that case, we can not pass UnprocessableEntityException.class to the Commons module, since we have to write a new handler method to pass violations to problemDetail object.

2024-03-08 07:11 UTC, ozgur-erste commented on src/main/java/com/iotiq/commons/exceptions/UnprocessableEntityException.java
> +public class UnprocessableEntityException extends ApplicationException {
refactored.

2024-03-08 07:12 UTC, ozgur-erste commented on src/main/java/com/iotiq/commons/exceptions/UnprocessableEntityException.java
> +        super(HttpStatus.UNPROCESSABLE_ENTITY, "unprocessableEntity", new LinkedList<>(), new Object[]{});
to be determined later.

2024-03-08 07:13 UTC, ozgur-erste commented on src/main/java/com/iotiq/commons/config/ExceptionHandlerAdvice.java
> +    }
done.

2024-03-22 13:16 UTC, inciotiq commented
The issue was discussed and the decision was to go in a different direction

2024-03-22 13:16 UTC, closed without merging